spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_service
    username: postgres
    password: Akash@2002
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9091

resilience4j:
  ratelimiter:
    instances:
      get-all-restaurant-rate-limiter:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms
